<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGdinwxi\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGdinwxi/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerGdinwxi.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerGdinwxi\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerGdinwxi\appProdProjectContainer([
    'container.build_hash' => 'Gdinwxi',
    'container.build_id' => '91ebdfcc',
    'container.build_time' => 1553037648,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGdinwxi');
