<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_ck_editor.command.installer' shared service.

$this->services['fos_ck_editor.command.installer'] = $instance = new \FOS\CKEditorBundle\Command\CKEditorInstallerCommand(${($_ = isset($this->services['fos_ck_editor.installer']) ? $this->services['fos_ck_editor.installer'] : ($this->services['fos_ck_editor.installer'] = new \FOS\CKEditorBundle\Installer\CKEditorInstaller())) && false ?: '_'});

$instance->setName('ckeditor:install');

return $instance;
