<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_ck_editor.config_manager' shared service.

return $this->services['fos_ck_editor.config_manager'] = new \FOS\CKEditorBundle\Model\ConfigManager();
