<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAphkryp\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAphkryp/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerAphkryp.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerAphkryp\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerAphkryp\appDevDebugProjectContainer([
    'container.build_hash' => 'Aphkryp',
    'container.build_id' => '45af3617',
    'container.build_time' => 1556985491,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAphkryp');
