<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2ztffpi\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2ztffpi/appProdProjectContainer.php') {
    touch(__DIR__.'/Container2ztffpi.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container2ztffpi\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container2ztffpi\appProdProjectContainer([
    'container.build_hash' => '2ztffpi',
    'container.build_id' => '43a22d7e',
    'container.build_time' => 1554674580,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2ztffpi');
